### ISSUE TITLE
latest(ver 4.0.0~) gensim cannot load chiVe KeyedVector format data

### ISSUE THREAD

**Issue by Neetless** [WorksApplications/chiVe#4]
When I tried this chiVe data for gensim, I got an error as below.

tried: `vectors = gensim.models.KeyedVectors.load("./chive-1.2-mc15_gensim/chive-1.2-mc15.kv")`
got: `ModuleNotFoundError: No module named 'gensim.models.deprecated'`

I found out that gensim's update cause this error. The latest gensim has `gensim.models.keyedvectors` instead of `gensim.models.deprecated.keyedvectors`.

So it's helpful if your chiVe data sets are updated or there are some comments in readme.

There is a workaround just deleting '.deprecated' in the 3rd row in kv data file.

**Comment by t-yamamura** [comment]
@Neetless 
Thanks for the report!
I found that some models can't be loaded in the latest version of gensim, such as `chive-1.2-mc15.kv`, `chive-1.2-mc30.kv`, `chive-1.2-mc90.kv`.
So, I will update these models to be able to load them.

> There is a workaround just deleting '.deprecated' in the 3rd row in kv data file.

Could you tell me how to delete `.deprecated` in the models?
I want to know an easy way to do it.

**Comment by Neetless** [comment]
@t-yamamura 
I just used vim :)

`vim chive-1.2-mc15.kv`
![image](https://user-images.githubusercontent.com/7441808/122032140-52dad500-ce0a-11eb-9d9f-95a949ba6314.png)

and just replace `gensim.models.deprecated.keyedvectors` to `gensim.models.keyedvectors` in the 3rd row.

**Comment by t-yamamura** [comment]
@Neetless 
Sorry for being late.
We have modified those models to load in the latest version of gensim.
